apiVersion: v2
name: mysqldump
description: git backup
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/mariadb/server/tree/10.5/client
type: application
version: 0.1.0
appVersion: "10.5.11-r0"
dependencies:
- name: liblocal
  version: 0.1.0
  repository: file://../liblocal
