# Default values for artifactory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
dbHost: db00
extraJavaOptions: -Xms1g -Xmx4g
mysqlConnectorVersion: 5.1.40
strategy:
  type: Recreate
tz: UTC
  
image:
  repository: docker.bintray.io/jfrog/artifactory-oss
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  clusterIP: None
  type: ClusterIP
  ports:
  - { port: 80, targetPort: http, protocol: TCP }

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-access-log: "false"
  hosts:
  - host: repo.example.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: tls-artifactory
    hosts:
    - repo.example.com

ingressTOTP:
  enabled: true
  className: ""
  annotations: {}
  hosts:
  - host: repo.example.com
    paths:
    - path: /artifactory/webapp/[#]/login
      pathType: Prefix
    - path: /artifactory/ui/(oauth2/loginRequest|auth/login)
      pathType: Prefix
  tls:
  - secretName: tls-artifactory
    hosts:
    - repo.example.com
  
resources:
  limits:
    memory: 4Gi
  requests:
    cpu: 200m
    memory: 1Gi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
