apiVersion: v2
name: ddclient
description: Dynamic-DNS client
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/ddclient/ddclient/
type: application
version: 0.1.0
appVersion: "3.9.1-r0"
dependencies:
- name: liblocal
  version: 0.1.0
  repository: file://../liblocal
