version: "3.1"

services:
  app:
    # image: ${REGISTRY_URI:-instantlinux}/weewx:latest
    # restart: always
    image: weewx:testing
    environment:
      ALTITUDE: 100, foot
      COMPUTER_TYPE: ${WX_COMPUTER:-Unbranded}
      DB_HOST: ${DB_HOST:-db00}
      DB_USER: wx
      LATITUDE: ${WX_LATITUDE:-38.898}
      LONGITUDE: ${WX_LONGITUDE:--77.037}
      LOCATION: ${WX_LOCATION:-Local Weather Station}
      OPERATOR: ${WX_OPERATOR:-Al Roker}
      OPTIONAL_ACCESSORIES: ${WX_OPTIONAL_ACC:-False}
      RAIN_YEAR_START: ${WX_RAIN_YEAR_START:-7}
      RSYNC_DEST: ${WX_RSYNC_DEST:-/usr/share/nginx/html}
      RSYNC_HOST: ${WX_RSYNC_HOST:-web01}
      RSYNC_PORT: ${PORT_WX_SSH:-22}
      SKIN: WeeGreen
      STATION_ID: ${WX_STATION_ID}
      STATION_FEATURES: ${WX_STATION_FEATURES:- }
      STATION_MODEL: ${WX_STATION_MODEL:-6152}
      STATION_TYPE: ${WX_STATION_TYPE:-Vantage}
      STATION_URL: ${WX_STATION_URL:- }
      SYSLOG_DEST: "@@${RSYSLOGD_HOST:-syslog}:${PORT_RSYSLOGD:-514}"
      TZ: ${TZ:-UTC}
      TZ_CODE: 4
      XTIDE_LOCATION: San Francisco
      WEBCAM_URL: ${WX_WEBCAM_URL:-https://www.wunderground.com/wundermap?lat=37.761&lon=-122.435&zoom=5&radar=1&cam=1}
    tmpfs:
    - /var/www/weewx
    # devices:
    # - /dev/ttyUSB0:/dev/ttyUSB0
    network_mode: bridge
    secrets:
    - weewx-db-password
    - weewx-rsync-sshkey
    - weewx-wunderground-apikey
    - weewx-wunderground-password

secrets:
  weewx-db-password:
    file: /var/adm/secrets/weewx-db-password
  weewx-rsync-sshkey:
    file: /var/adm/secrets/weewx-rsync-sshkey
  weewx-wunderground-apikey:
    file: /var/adm/secrets/weewx-wunderground-apikey
  weewx-wunderground-password:
    file: /var/adm/secrets/weewx-wunderground-password
