---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: AIRLINK_HOST, value: $WX_AIRLINK_HOST }
        - { name: ALTITUDE, value: "100, foot" }
        - { name: COMPUTER_TYPE, value: $WX_COMPUTER }
        - { name: DB_HOST, value: $DB_HOST }
        - { name: DB_USER, value: wx }
        - { name: LATITUDE, value: "37.75" }
        - { name: LONGITUDE, value: "-122.4" }
        - { name: LOCATION, value: "The Castro, San Francisco, CA" }
        - { name: OPERATOR, value: "$WX_OPERATOR" }
        - { name: OPTIONAL_ACCESSORIES, value: "$WX_OPTIONAL_ACC" }
        - { name: RAIN_YEAR_START, value: "$WX_RAIN_YEAR_START" }
        - { name: RSYNC_DEST, value: $WX_RSYNC_DEST }
        - { name: RSYNC_HOST, value: $WX_RSYNC_HOST }
        - { name: RSYNC_PORT, value: "$PORT_WX_SSH" }
        - { name: SKIN, value: WeeGreen }
        - { name: STATION_ID, value: $WX_STATION_ID }
        - { name: STATION_FEATURES, value: "$WX_STATION_FEATURES" }
        - { name: STATION_MODEL, value: "$WX_STATION_MODEL" }
        - { name: STATION_TYPE, value: $WX_STATION_TYPE }
        - { name: STATION_URL, value: "$WX_STATION_URL" }
        - { name: SYSLOG_DEST, value: "@@$RSYSLOGD_IP:$PORT_RSYSLOGD" }
        - { name: TZ, value: $TZ }
        - { name: TZ_CODE, value: "4" }
        - { name: WEBCAM_URL, value: "$WX_WEBCAM_URL" }
        - { name: XTIDE_LOCATION, value: San Francisco }
        image: $REGISTRY_URI/$SERVICE_NAME:$VERSION_WEEWX
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 64Mi
        # TODO: better security, see
        # https://github.com/kubernetes/kubernetes/issues/60748
        securityContext:
          privileged: true
        volumeMounts:
        - name: usb
          mountPath: /dev/ttyUSB0
        - name: var
          mountPath: /var/www/weewx
        - name: weewx-db-password
          mountPath: /run/secrets/weewx-db-password
          readOnly: true
          subPath: weewx-db-password
        - name: weewx-rsync-sshkey
          mountPath: /run/secrets/weewx-rsync-sshkey
          readOnly: true
          subPath: weewx-rsync-sshkey
        - name: weewx-wunderground-apikey
          mountPath: /run/secrets/weewx-wunderground-apikey
          readOnly: true
          subPath: weewx-wunderground-apikey
        - name: weewx-wunderground-password
          mountPath: /run/secrets/weewx-wunderground-password
          readOnly: true
          subPath: weewx-wunderground-password
      imagePullSecrets: [ $IMAGEPULL_SPEC ]
      nodeSelector:
        service.$SERVICE_NAME: allow
      volumes:
      - name: usb
        hostPath: { path: /dev/ttyUSB0 }
      - name: var
        emptyDir: { medium: Memory }
      - name: weewx-db-password
        secret:
          secretName: weewx-db-password
      - name: weewx-rsync-sshkey
        secret:
          secretName: weewx-rsync-sshkey
      - name: weewx-wunderground-apikey
        secret:
          secretName: weewx-wunderground-apikey
      - name: weewx-wunderground-password
        secret:
          secretName: weewx-wunderground-password
