---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: $SERVICE_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: HOST, value: $DYNAMIC_HOSTNAME }
        image: $REGISTRY_URI/$SERVICE_NAME:$VERSION_EZ_IPUPDATE
        volumeMounts:
        - name: secret
          mountPath: /run/secrets/ez-ipupdate-user
          subPath: ez-ipupdate-user
      dnsConfig:
        options: [ name: ndots ]
      imagePullSecrets: [ $IMAGEPULL_SPEC ]
      volumes:
      - name: secret
        secret:
          secretName: ez-ipupdate-user
