apiVersion: v2
name: guacamole
description: Apache Guacamole remote desktop service
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/apache/guacamole-client
- https://github.com/apache/guacamole-server
type: application
version: 0.1.0
appVersion: "1.16.0"
