# Default values for guacamole.
guacd:
  deployment:
    resources:
      limits:
        memory: 1536Mi
      requests:
        cpu: 100m
        memory: 512Mi
guacamole-server:
  tlsHostname: guacamole.example.com
  deployment:
    env:
      guacd_hostname: $(GUACD_SERVICE_HOST)
      guacd_port: $(GUACD_SERVICE_PORT)
      mysql_database: guacamole
      mysql_hostname: db00
      mysql_user: guacamole_user
    xenv:
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: guacamole-db-password
          key: guacamole-db-password
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 768Mi
