---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  clusterIP: None
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: $SERVICE_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: OX_CONFIG_DB_HOST, value: $OX_CONFIG_DB_HOST }
        - { name: OX_SERVER_MEMORY, value: "$OX_SERVER_MEMORY" }
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/open-xchange-appsuite:$VERSION_OX_APPSUITE
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 4096Mi
          requests:
            cpu: 200m
            memory: ${OX_SERVER_MEMORY}Mi
        volumeMounts:
        - mountPath: /ox/etc
          name: share
          readOnly: $OX_ETC_READONLY
          subPath: ox-appsuite/etc
        - mountPath: /var/opt/filestore
          name: share
          subPath: ox-appsuite/data
        - mountPath: /opt/open-xchange/appsuite/apps/themes
          name: share
          subPath: ox-appsuite/themes
        - mountPath: /var/log/open-xchange
          name: logs
        - mountPath: /var/log/apache2
          name: apache2
        - name: ox-db-password
          mountPath: /run/secrets/ox-db-password
          subPath: ox-db-password
        - name: ox-admin-password
          mountPath: /run/secrets/ox-admin-password
          subPath: ox-admin-password
        - name: ox-master-password
          mountPath: /run/secrets/ox-master-password
          subPath: ox-master-password
      dnsConfig:
        options:
        - name: use-vc
        - name: ndots
      imagePullSecrets: [ $IMAGEPULL_SPEC ]
      volumes:
      - name: share
        hostPath: { path: $PATH_SHR }
      - name: logs
        emptyDir: {}
      - name: apache2
        emptyDir: {}
      - name: ox-db-password
        secret:
          secretName: ox-db-password
      - name: ox-admin-password
        secret:
          secretName: ox-admin-password
      - name: ox-master-password
        secret:
          secretName: ox-master-password
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $SERVICE_NAME-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1024m
    nginx.ingress.kubernetes.io/enable-access-log: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
spec:
  tls:
  - secretName: tls-$SERVICE_NAME
    hosts:
    - $SERVICE_NAME.$DOMAIN
  rules:
  - host: $SERVICE_NAME.$DOMAIN
    http:
      paths:
      - path: /
        backend:
          service:
            name: $SERVICE_NAME
            port:
              number: 80
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $SERVICE_NAME-totp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://$AUTHELIA_IP/api/verify
    nginx.ingress.kubernetes.io/auth-signin: https://authtotp.$DOMAIN
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
  - secretName: tls-$SERVICE_NAME
    hosts:
    - $SERVICE_NAME.$DOMAIN
  rules:
  - host: $SERVICE_NAME.$DOMAIN
    http:
      paths:
      - path: /(appsuite/$DOL|appsuite/api/login|appsuite/ui$DOL)
        backend:
          service:
            name: $SERVICE_NAME
            port:
              number: 80
        pathType: Prefix
