apiVersion: v2
name: postfix
description: Postfix with python
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/vdukhovni/postfix
type: application
version: 0.1.0
appVersion: "3.6.1-r0"
dependencies:
- name: liblocal
  version: 0.1.0
  repository: file://../liblocal
