version: "3.1"

services:
  app:
    image: jasonrivers/nagios:${VERSION_NAGIOS:-latest}
    restart: always
    hostname: nagios.${DOMAIN}
    # If your local plugins require additional packages, this is
    # where to add them (if it's a large number, create a new image).
    # Can also change image's postfix port if network_mode:host.
    command: >
      bash -c "pip install mysql-python &&
      apt-get update &&
      apt-get install -y mariadb-client python3-pymysql &&
      chmod u+s /opt/nagios/libexec/check_dhcp &&
      [ -e /usr/local/nagios ] || ln -s /opt/nagios /usr/local/nagios &&
      sed -i -e 's/^smtp      inet/2525 inet/' /etc/postfix/master.cf &&
      sed -i -e 's:find /opt/nagios :#find /opt/nagios :' /etc/service/nagios/run &&
      sed -i -e 's/nagiosadmin/$USER,iphone7/' /opt/nagios/etc/cgi.cfg &&
      cp /run/secrets/nagios-htpasswd /opt/nagios/etc/htpasswd.users &&
      /usr/local/bin/start_nagios"
    environment:
      MAIL_RELAY_HOST: ${NAGIOS_MAIL_RELAY:-smtp}
      NAGIOS_TIMEZONE: ${TZ:-UTC}
      TZ: ${TZ:-UTC}
    volumes:
    - bin:/opt/nagios/bin
    - etc:/opt/nagios/etc
    - graph:/opt/nagiosgraph
    - var:/opt/nagios/var
    - ${ADMIN_PATH:-/opt}/nagios/plugins:/opt/nagios/plugins:ro
    ports:
    - 80:80
    secrets:
    - nagios-htpasswd
    network_mode: host

  nagiosql:
    image: instantlinux/nagiosql:${VERSION_NAGIOSQL:-latest}
    restart: always
    hostname: nagiosql
    environment:
      DB_HOST: ${DB_HOST:-db00}
      TZ: ${TZ:-UTC}
    volumes:
    - bin:/opt/nagios/bin
    - config:/var/www/nagiosql/config
    - etc:/opt/nagios/etc
    - var:/opt/nagios/var
    ports:
    - ${PORT_NAGIOSQL:-8080}:80
    secrets:
    - nagiosql-db-password
    network_mode: bridge

  nginx:
    image: nginx:${VERSION_NGINX:-latest}
    restart: always
    hostname: monitor
    ports:
    - ${PORT_MONITOR_SSL:-443}:443
    - ${PORT_MONITOR_HTTP:-80}:80
    volumes:
    - ${ADMIN_PATH:-/opt}/nagios/etc/nginx/conf.d:/etc/nginx/conf.d:ro
    - ${SHARE_PATH:-/opt}/common/pki/ca:/etc/ssl/ca:ro
    - ${SHARE_PATH:-/opt}/common/pki/certs:/etc/ssl/certs:ro
    environment:
      TZ: ${TZ:-UTC}
    secrets:
    - monitor.${DOMAIN:-demo}-server-key.pem
    depends_on:
    - app
    - nagiosql
    network_mode: bridge
  
volumes:
  bin:
  config:
  etc:
  graph:
  var:

secrets:
  nagios-htpasswd:
    file: /var/adm/secrets/nagios-htpasswd
  nagiosql-db-password:
    file: /var/adm/secrets/nagiosql-db-password
  monitor.ci.net-server-key.pem:
    file: ${ADMIN_PATH}/../tls/monitor.ci.net-server-key.pem
