---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  clusterIP: None
  ports:
  - { port: 80, targetPort: 8080 }
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: $SERVICE_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: ATL_DB_DRIVER, value: com.mysql.jdbc.Driver }
        - { name: ATL_DB_SCHEMA_NAME, value: $JIRA_DB_SCHEMA }
        # Note - vendor doesn't support mariadb 10.4+ but it works fine
        - { name: ATL_DB_TYPE, value: mysql }
        - { name: ATL_JDBC_URL,
            value: "jdbc:mysql://$DB_HOST:3306/$JIRA_DB_SCHEMA?useUnicode=true&amp;characterEncoding=UTF8&amp;sessionVariables=default_storage_engine=InnoDB" }
        - { name: ATL_JDBC_USER, value: $JIRA_DB_USER }
        - { name: ATL_PROXY_NAME, value: jira.$DOMAIN }
        - { name: ATL_PROXY_PORT, value: "443" }
        - { name: ATL_TOMCAT_SCHEME, value: https }
        - { name: ATL_TOMCAT_SECURE, value: "true" }
        - { name: JVM_MINIMUM_MEMORY, value: 1536m }
        - { name: JVM_MAXIMUM_MEMORY, value: 2048m }
        - { name: JVM_SUPPORT_RECOMMENDED_ARGS,
            value: -Datlassian.plugins.enable.wait=600 }
        - { name: TZ, value: $TZ }
        - name: ATL_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: jira-db-password
              name: jira-db-password
        image: atlassian/jira-core:$VERSION_JIRA
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 6144Mi
          requests:
            cpu: 300m
            memory: 2048Mi
        volumeMounts:
        - mountPath: /var/atlassian/application-data/jira
          name: $SERVICE_NAME
          subPath: home
        - mountPath: /opt/atlassian/jira/lib/mysql-connector-java-8.0.22.jar
          name: $SERVICE_NAME
          readOnly: true
          subPath: mysql-connector/mysql-connector-java-8.0.22.jar
        - mountPath: /opt/atlassian/jira/conf/Catalina/localhost
          name: $SERVICE_NAME
          subPath: catalina
        - mountPath: /opt/atlassian/jira/logs
          name: $SERVICE_NAME
          subPath: logs
      nodeSelector:
        service.$SERVICE_NAME: allow
      volumes:
      - name: $SERVICE_NAME
        hostPath: { path: $K8S_VOLUMES_PATH/$SERVICE_NAME }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $SERVICE_NAME-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-access-log: "false"
spec:
  tls:
  - secretName: tls-$SERVICE_NAME
    hosts:
    - $SERVICE_NAME.$DOMAIN
  rules:
  - host: $SERVICE_NAME.$DOMAIN
    http:
      paths:
      - path: /
        backend:
          service:
            name: $SERVICE_NAME
            port:
              number: 80
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $SERVICE_NAME-totp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://$AUTHELIA_IP/api/verify
    nginx.ingress.kubernetes.io/auth-signin: https://authtotp.$DOMAIN
spec:
  tls:
  - secretName: tls-$SERVICE_NAME
    hosts:
    - $SERVICE_NAME.$DOMAIN
  rules:
  - host: $SERVICE_NAME.$DOMAIN
    http:
      paths:
      - path: /login.jsp
        backend:
          service:
            name: $SERVICE_NAME
            port:
              number: 80
        pathType: Prefix
