# Note -- if container won't start because password hasn't been set, create
#  a user-seed.conf in mounted volume. Details are found at:
#  http://docs.splunk.com/Documentation/Splunk/latest/Admin/user-seedconf
#
# The free version of splunk does not have login splash page. Below are
#  ingress definitions that define basic-auth and TOTP. Add a k8s secret
#  named splunk-auth containing a key named auth. See this URL:
#  https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/auth/basic/README.md

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  clusterIP: None
  ports:
  - name: $SERVICE_NAME
    port: 80
    targetPort: 8000
  - name: syslog
    port: $PORT_SPLUNK_SYSLOG
    targetPort: 1514
  - name: hec
    port: 8088
    targetPort: 8088
  - name: api
    port: 8089
    targetPort: 8089
  - name: forwarder
    port: 9997
    targetPort: 9997
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
    release: "0.1"
  name: $SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: $SERVICE_NAME
      release: "0.1"
  serviceName: $SERVICE_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
        release: "0.1"
    spec:
      containers:
      - name: $SERVICE_NAME
        command: [/bin/sh]
        args:
        # The image lacks tzdata, this looks up and installs rpm
        - -c
        - >
          source /etc/os-release && cd /tmp &&
          PKG=`rpm -q tzdata`.rpm &&
          DIST=`wget -qO- http://mirror.centos.org/centos|
            egrep -o "href=\"${DOL}{VERSION_ID}\.[0-9]+"|cut -d\" -f 2` &&
          curl -Lo ${DOL}PKG \
            http://mirror.centos.org/centos/${DOL}{DIST}/BaseOS/x86_64/os/Packages/${DOL}PKG &&
          sudo rpm --import https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official &&
          sudo rpm -ivh --reinstall ${DOL}PKG &&
          exec /sbin/entrypoint.sh start-service
        env:
        - { name: SPLUNK_ADD, value: tcp 1514 }
        - { name: SPLUNK_ENABLE_LISTEN, value: "9997" }
        - { name: SPLUNK_PASSWORD, value: changeme }
        - { name: SPLUNK_START_ARGS, value: --accept-license --answer-yes }
        image: splunk/splunk:$VERSION_SPLUNK
        ports:
        - containerPort: 8000
        - containerPort: 1514
        - containerPort: 8088
        - containerPort: 8089
        - containerPort: 9997
        resources:
          limits:
            memory: 4096Mi
          requests:
            cpu: 200m
            memory: 384Mi
        volumeMounts:
        - mountPath: /opt/splunk/etc
          name: splunk
          subPath: etc
        - mountPath: /opt/splunk/var
          name: splunk
          subPath: var
      nodeSelector:
        service.$SERVICE_NAME: allow
  volumeClaimTemplates:
  - metadata:
      name: $SERVICE_NAME
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 50Mi
      selector:
        matchLabels:
          volume.group: $SERVICE_NAME
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $SERVICE_NAME-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: splunk-auth
    nginx.ingress.kubernetes.io/enable-access-log: "false"
spec:
  tls:
  - secretName: tls-$SERVICE_NAME
    hosts:
    - $SERVICE_NAME.$DOMAIN
  rules:
  - host: $SERVICE_NAME.$DOMAIN
    http:
      paths:
      - path: /
        backend:
          service:
            name: $SERVICE_NAME
            port:
              number: 80
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $SERVICE_NAME-totp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://$AUTHELIA_IP/api/verify
    nginx.ingress.kubernetes.io/auth-signin: https://authtotp.$DOMAIN
spec:
  tls:
  - secretName: tls-$SERVICE_NAME
    hosts:
    - $SERVICE_NAME.$DOMAIN
  rules:
  - host: $SERVICE_NAME.$DOMAIN
    http:
      paths:
      - path: /en-US/account/login
        backend:
          service:
            name: $SERVICE_NAME
            port:
              number: 80
        pathType: Prefix
