---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  clusterIP: $WX_NGINX_IP
  ports:
  - { port: $PORT_WX_SSH, targetPort: 22, name: ssh }
  - { port: 80, targetPort: 80, name: $SERVICE_NAME }
  selector:
    app.kubernetes.io/name: $SERVICE_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: $SERVICE_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        command: [/bin/sh]
        args:
        - -c
        - >
          apk add --update --no-cache openssh rsync &&
          ssh-keygen -A && /usr/sbin/sshd &&
          adduser -u 2060 -s /bin/sh -g Weather -D wx &&
          passwd -u wx &&
          mkdir -p $WX_RSYNC_DEST &&
          chown wx $WX_RSYNC_DEST &&
          mkdir -m 700 /home/wx/.ssh &&
          cp /run/id_rsa.pub /home/wx/.ssh/authorized_keys &&
          chown -R wx /home/wx/.ssh &&
          exec /usr/sbin/nginx -g 'daemon off;'
        image: nginx:$VERSION_NGINX
        ports:
        - containerPort: 22
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/wx.conf
          name: config
          readOnly: true
          subPath: wx.conf
        - mountPath: /run/id_rsa.pub
          name: weewx-rsync-sshkey
          readOnly: true
          subPath: id_rsa.pub
        - mountPath: /etc/ssh
          name: share
          subPath: $SERVICE_NAME/etc/ssh
        - mountPath: $WX_RSYNC_DEST
          name: html
      dnsConfig:
        options: [ name: ndots ]
      volumes:
      - name: config
        configMap:
          name: $SERVICE_NAME
      - name: share
        hostPath: { path: $PATH_SHR }
      - name: html
        emptyDir: { medium: Memory, sizeLimit: 50Mi }
      - name: weewx-rsync-sshkey
        secret:
          secretName: weewx-rsync-sshkey
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $SERVICE_NAME-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: wx.$DOMAIN
    http:
      paths:
      - path: /
        backend:
          service:
            name: $SERVICE_NAME
            port:
              number: 80
        pathType: Prefix
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: $SERVICE_NAME
data:
  wx.conf: |
    access_log /dev/stdout;
    error_log stderr;

    server {
      listen       80;
      server_name  wx.$DOMAIN;
      index        forecast.html;

      location / {
        root /usr/share/nginx/wx;
      }
    }
