apiVersion: v2
name: mythtv-backend
description: MythTV DVR backend
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/mythtv/mythtv
type: application
version: 0.1.0
appVersion: "31.0-fixes.202106102123.0680b37c68"
dependencies:
- name: liblocal
  version: 0.1.0
  repository: file://../liblocal
