---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
  name: $SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: $SERVICE_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: HOUR, value: "5" }
        - { name: SERVERS, value: "$DB_SERVERS" }
        - { name: SKEW_SECONDS, value: "30" }
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/$SERVICE_NAME:$VERSION_MYSQLDUMP
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/backup
          name: backup
          subPath: $SERVICE_NAME
        - mountPath: /var/log
          name: logs
        - name: mysql-backup-creds
          mountPath: /run/secrets/mysql-backup-creds
          subPath: mysql-backup-creds
      dnsConfig:
        options: [ name: ndots ]
      imagePullSecrets: [ $IMAGEPULL_SPEC ]
      nodeSelector:
        service.$SERVICE_NAME: allow
      volumes:
      - name: backup
        hostPath: { path: $PATH_BKP }
      - name: logs
        hostPath: { path: $K8S_VOLUMES_PATH/sync-logs/$SERVICE_NAME }
      - name: mysql-backup-creds
        secret:
          secretName: mysql-backup-creds
