# Default values for ez-ipupdate.
env:
  host: www.example.com
volumeMounts:
- name: secret
  mountPath: /run/secrets/ez-ipupdate-user
  subPath: ez-ipupdate-user
volumes:
- name: secret
  secret:
    secretName: ez-ipupdate-user

image:
  repository: instantlinux/ez-ipupdate
  pullPolicy: IfNotPresent
  tag: "3.0.10-r9"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deployment: {}
serviceAccount: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  enabled: false

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
