apiVersion: v2
name: blacklist
description: DNS blacklist for spamassassin
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/spamhaus/rbldnsd
type: application
version: 0.1.0
appVersion: "0.998b"
dependencies:
- name: liblocal
  version: 0.1.0
  repository: file://../liblocal
