# Default values for blacklist.
statefulset:
  containerPorts:
  - { containerPort: 53, protocol: UDP }
  env:
    db_host: db00
    ns_servers: blacklist-k8s.example.com
    rbl_domain: blacklist.example.com
    tz: UTC
  replicas: 2
volumeMounts:
- mountPath: /var/lib/rbldns
  name: data
- name: mysql-blacklist-user
  mountPath: /run/secrets/mysql-blacklist-user
  subPath: mysql-blacklist-user
volumes:
- name: mysql-blacklist-user
  secret:
    secretName: mysql-blacklist-user
volumeClaimTemplates:
- metadata:
    name: data
  spec:
    accessModes: [ ReadWriteOnce ]
    resources:
      requests:
        storage: 500Mi

image:
  repository: instantlinux/blacklist
  pullPolicy: IfNotPresent
  tag: "0.998b"

nameOverride: ""
fullnameOverride: ""

serviceAccount: {}
service:
  clusterIP: 10.101.1.10
  ports:
  - { port: 53, protocol: UDP, targetPort: 53 }
  type: clusterIP
autoscaling:
  enabled: false
