apiVersion: v2
name: weewx
description: Weather Station software
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/weewx/weewx/
type: application
version: 0.1.3
appVersion: "4.8.0"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
