apiVersion: v2
name: weewx
description: Weather Station software
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/weewx/weewx/
type: application
version: 0.1.0
appVersion: "4.5.1"
dependencies:
- name: liblocal
  version: 0.1.0
  repository: file://../liblocal
