apiVersion: v2
name: wxcam-upload
description: Uploader for Weather Underground images
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/proftpd/proftpd
type: application
version: 0.1.0
appVersion: "1.3.7a-r0"
dependencies:
- name: chartlib
  version: 0.1.1
  repository: https://instantlinux.github.io/docker-tools
- name: data-sync
  version: 0.1.1
  repository: https://instantlinux.github.io/docker-tools
