apiVersion: v2
name: rsyslogd
description: rsyslogd
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/rsyslog/rsyslog
type: application
version: 0.1.0
appVersion: "8.2012.0-r0"
dependencies:
- name: liblocal
  version: 0.1.0
  repository: file://../liblocal
