apiVersion: v2
name: git-dump
description: git backup
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
type: application
version: 0.1.0
appVersion: "2.30.2-r0"
dependencies:
- name: liblocal
  version: 0.1.0
  repository: file://../liblocal
