---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME
    release: "0.1"
  name: $SERVICE_NAME
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: $SERVICE_NAME
      release: "0.1"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME
        release: "0.1"
    spec:
      containers:
      - name: $SERVICE_NAME
        env:
        - { name: GIT_COMMIT, value: master }
        - { name: GIT_HOST, value: "$GIT_HOST" }
        - { name: GIT_REPO, value: "$GIT_REPO" }
        - { name: INTERVAL, value: "60" }
        image: $REGISTRY_URI/git-pull:$VERSION_GIT_PULL
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 32Mi
        volumeMounts:
        - name: admin
          mountPath: /git
        - name: sshkey
          mountPath: /run/secrets/git-deploy-sshkey
          readOnly: true
          subPath: git-deploy-sshkey
      dnsConfig:
        options: [ name: ndots ]
      imagePullSecrets: [ $IMAGEPULL_SPEC ]
      volumes:
      - name: admin
        hostPath:
          path: $PATH_ADM
      - name: sshkey
        secret:
          secretName: git-deploy-sshkey
