apiVersion: v2
name: gitlab
description: Gitlab CI/CD
home: https://github.com/instantlinux/docker-tools
sources:
- https://hub.docker.com/r/gitlab/gitlab-ce
- https://github.com/instantlinux/docker-tools
- https://gitlab.com/gitlab-org/gitlab
type: application
version: 0.1.2
appVersion: "13.11.3-ce.0"
dependencies:
- name: chartlib
  version: 0.1.5
  # repository: https://instantlinux.github.io/docker-tools
  repository: file://../chartlib
