apiVersion: v2
name: mt-daapd
description: Dynamic-DNS client
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://sourceforge.net/projects/mt-daapd/
type: application
version: 0.1.0
appVersion: "26.4-dfsg1-1"
dependencies:
- name: liblocal
  version: 0.1.0
  repository: file://../liblocal
