apiVersion: v2
name: nextcloud
description: Nextcloud file-sharing and application server
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
type: application
version: 0.1.0
appVersion: "20.0.7"
dependencies:
- name: liblocal
  version: 0.1.0
  repository: file://../liblocal
