apiVersion: v2
name: data-sync
description: git backup
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
type: application
version: 0.1.1
appVersion: "2.51.4-4.12.0-r0"
dependencies:
- name: chartlib
  version: 0.1.3
  repository: https://instantlinux.github.io/docker-tools
