name: Release Helm Charts

on:
  push:
    branches:
    - master
    inputs:
      charts_dir: k8s/helm

lint-chart:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Run chart-testing (lint)
      uses: helm/chart-testing-action@v2.1.0
      with:
        command: lint
        config: .github/ct.yaml
