apiVersion: v2
name: dovecot
description: Dovecot imapd server
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/vdukhovni/dovecot
type: application
version: 0.1.1
appVersion: "2.3.15-r0"
dependencies:
- name: chartlib
  version: 0.1.7
  repository: https://instantlinux.github.io/docker-tools
- name: data-sync
  version: 0.1.2
  repository: https://instantlinux.github.io/docker-tools
